---

-   name: enable features - bgp ospf pim
    cisco.nxos.nxos_feature:
      feature: "{{ item.feature }}"
    loop: "{{ features }}"

-   name: configure underlay ospf
    cisco.nxos.nxos_ospfv2:
      config:
        processes:
          - process_id: "{{ ospf_process_id }}"
            router_id: "{{ router_id }}"
      state: merged
